previewsEnabled: true
services:
  # Fullstack JS DEV
  - type: web
    name: Fullstack JS - Back
    branch: dev
    env: node
    buildCommand: yarn install && yarn build:dev
    startCommand: yarn start

    # Fullstack JS STAGING
  - type: web
    name: Fullstack JS - Back
    branch: staging
    env: node
    buildCommand: yarn install && yarn build:staging
    startCommand: yarn start

  # Fullstack JS PROD
  - type: web
    name: Fullstack JS - Back
    branch: master
    env: node
    buildCommand: yarn install && yarn build:master
    startCommand: yarn start
