services:
  - type: web
    name: Fullstack JS [DEV]
    region: frankfurt
    plan: starter
    branch: master
    env: node
    buildCommand: yarn install && yarn build:dev
    startCommand: yarn serve
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fullstackjs-dev
          property: connectionString

databases:
  - name: fullstackjs-dev
    region: frankfurt
    plan: starter
    user: ubidreams
