name: Release

on:
  push:
    branches:
      - master
      - dev

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Release type
        run: echo "IS_PRERELEASE=$([[ ${{ github.ref }} == *"-"* ]] && echo true || echo false)" >> $GITHUB_ENV

      - name: Generate changelog body
        id: changelog
        run: |
          npx auto-changelog --template changelog-template.hbs --commit-limit false --starting-version ${{ github.ref }}
          cat CHANGELOG.md
          echo "::set-output name=release::$(cat CHANGELOG.md)"

      - name: Generate Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog.outputs.release}}
          draft: false
          prerelease: ${{ env.IS_PRERELEASE }}
