name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Release type
        run: echo "IS_PRERELEASE=$([[ ${{ github.ref }} == *"-"* ]] && echo true || echo false)" >> $GITHUB_ENV

      - name: Generate changelog body
        id: changelog
        run: npx auto-changelog --template changelog-template.hbs --commit-limit false

      - name: Test
        run: echo ${{steps.github_release.outputs.changelog}}
#      - name: Generate Release
#        uses: actions/create-release@latest
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: ${{ github.ref }}
#          body: ${{steps.github_release.outputs.changelog}}
#          draft: false
#          prerelease: ${{ env.IS_PRERELEASE }}
